name: Set Firebase Admin Claim

on:
  workflow_dispatch:
    inputs:
      uid:
        description: 'Firebase user UID to grant admin'
        required: true
        type: string

jobs:
  set-claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Write service account key
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Install deps
        run: npm ci || npm install firebase-admin
      - name: Run set-admin script
        run: node scripts/set-admin-claim.js ${{ github.event.inputs.uid }}
